secrets:
  db-passwd:
    file: .secrets/db-passwd
networks:
  default:
    name: prod-net
    external: true

services:
  nginx:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - ../nginx/conf/:/etc/nginx/conf.d/:ro
      - ../certbot/www:/var/www/certbot/:ro
  certbot:
    image: certbot:latest
    volumes: -../certbot/www:/var/www/certbot/:rw
  app:
    build: .
    image: bpt-server:latest
    container_name: bpt-production
    ports:
      - 80:80
    secrets:
      - db-passwd
    depends_on:
      database:
        condition: service_healthy
    env_file:
      - ./.env
  database:
    image: postgres
    container_name: db-production
    restart: always
    volumes:
      - /bpt/production/db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/db-passwd
      POSTGRES_DB: bpt
    secrets:
      - db-passwd
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
