secrets:
  db-passwd:
    file: .secrets/db-passwd
networks:
  default:
    name: stage-net
    external: true

services:
  nginx:
    image: nginx
    ports:
      - 4443:80 #Port 4443(staging) to outside and gunicorn runs on 80
    restart: always
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d/:ro # Read config from ./nginx
      - ../../certbot/www:/var/www/certbot/:ro
      - ../../certbot/conf/:/etc/nginx/ssl/:ro # Get certificates to nginx
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ../../certbot/www/:/var/www/certbot/:rw # Certbot uses to renew certificates ?
      - ../../certbot/conf/:/etc/letsencrypt/:rw # Location of certificates
  app-stage:
    secrets:
      - db-passwd
    build: .
    image: bpt-stage:latest
    container_name: bpt-stage
    ports:
      - 88:80
    depends_on:
      database-stage:
        condition: service_healthy
    env_file:
      - ./.env
  database-stage:
    image: postgres
    container_name: db-stage
    restart: always
    volumes:
      - /bpt/staging/db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/db-passwd
      POSTGRES_DB: bpt_stage
    secrets:
      - db-passwd
    networks:
      default:
        aliases:
          - database
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
