secrets:
  db-passwd:
    file: .secrets/db-passwd
networks:
  default:
    name: stage-net
    external: true

services:
  app-stage:
    volumes:
      - /etc/letsencrypt/live/berry-picker-tracker.cs.helsinki.fi:/etc/ssl
    secrets:
      - db-passwd
    build: .
    image: bpt-stage:latest
    container_name: bpt-stage
    ports:
      - 4443:80
    depends_on:
      database-stage:
        condition: service_healthy
    env_file:
      - ./.env
  database-stage:
    image: postgres
    container_name: db-stage
    restart: always
    volumes:
      - /bpt/staging/db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/db-passwd
      POSTGRES_DB: bpt_stage
    secrets:
      - db-passwd
    networks:
      default:
        aliases:
          - database
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
